### ISSUE TITLE
mac_apt analysis result DBs are insufficient

### ISSUE THREAD

**Issue by hiddenbytes** [mnrkbys/ma2tl#2]
Hi, I think I've ran into a bug using ma2tl on the latest mac_apt.

I am trying ma2tl on a mac_apt output (version 1.6.2.dev) but I am getting a 'Error: mac_apt analysis result DBs are insufficient.' error. 

Happy to provide additional logs etc if it helps!

**Comment by mnrkbys** [comment]
This message means that the databases required by ma2tl could not be found (confirm the source code of ma2tl).
What are the command lines of mac_apt and ma2tl?
You need to run mac_apt with ALL plugins.

**Comment by hiddenbytes** [comment]
Thank-you! I was trying to work it out for days!

I did not use 'ALL' when gathering the information from mac_apt. 

Fantastic tool, I look forward to following it's journey as it matures in the future!

For anyone else with the same issue, the commands I used to successfully run mac_apt and ma2tl were:

**_Mac_apt_**
python mac_apt.py -o _<<EVIDENCE File>>_ -x -d DMG _<<OUTPUT Location>>_ ALL

**_ma2tl_**
python3 ma2tl.py -i _<<mac_apt Output Folder>>_ -o _<<ma2tl output location>>_ -s '_<<Start Date>>_' -e '_<<End Date>>_' -ot XLSX ALL
